#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
    using Microsoft.Owin.Security;
    
    #line default
    #line hidden
    using Specter.Web;
    using Specter.Web.Core.Events;
    using Specter.Web.Core.Infrastructure;
    using Specter.Web.Framework;
    using Specter.Web.Framework.Events;
    using Specter.Web.Framework.Mvc;
    using Specter.Web.Framework.UI;
    using Specter.Web.Framework.UI.Captcha;
    
    #line 1 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
    using Specter.Web.Models;
    
    #line default
    #line hidden
    using Specter.Web.Models.Common;
    using Specter.Web.Models.Device;
    using Specter.Web.Models.Dialogs;
    using Specter.Web.Models.GeoZones;
    using Specter.Web.Models.GPS;
    using Specter.Web.Models.Map;
    using Specter.Web.Models.Notify;
    using Specter.Web.Models.User;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/_ExternalLoginsListPartial.cshtml")]
    public partial class _Views_Account__ExternalLoginsListPartial_cshtml : Specter.Web.Framework.ViewEngines.Razor.WebViewPage<ExternalLoginListViewModel>
    {
        public _Views_Account__ExternalLoginsListPartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<h4>Use another service to log in.</h4>\r\n<hr />\r\n");

            
            #line 7 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
  
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div>\r\n            <p>There are no external authentication services confi" +
"gured. See <a");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=313242\"");

WriteLiteral(">this article</a>\r\n            for details on setting up this ASP.NET application" +
" to support logging in via external services.</p>\r\n        </div>\r\n");

            
            #line 15 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
    }
    else
    {
        using (Html.BeginForm(Model.Action, "Account", new { ReturnUrl = Model.ReturnUrl }))
        {
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                    

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"socialLoginList\"");

WriteLiteral(">\r\n                <p>\r\n");

            
            #line 23 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                 foreach (AuthenticationDescription p in loginProviders)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteAttribute("id", Tuple.Create(" id=\"", 975), Tuple.Create("\"", 1001)
            
            #line 25 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
, Tuple.Create(Tuple.Create("", 980), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 980), false)
);

WriteLiteral(" name=\"provider\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1018), Tuple.Create("\"", 1047)
            
            #line 25 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                    , Tuple.Create(Tuple.Create("", 1026), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 1026), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1048), Tuple.Create("\"", 1092)
, Tuple.Create(Tuple.Create("", 1056), Tuple.Create("Log", 1056), true)
, Tuple.Create(Tuple.Create(" ", 1059), Tuple.Create("in", 1060), true)
, Tuple.Create(Tuple.Create(" ", 1062), Tuple.Create("using", 1063), true)
, Tuple.Create(Tuple.Create(" ", 1068), Tuple.Create("your", 1069), true)
            
            #line 25 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                                                                   , Tuple.Create(Tuple.Create(" ", 1073), Tuple.Create<System.Object, System.Int32>(p.Caption
            
            #line default
            #line hidden
, 1074), false)
, Tuple.Create(Tuple.Create(" ", 1084), Tuple.Create("account", 1085), true)
);

WriteLiteral(">");

            
            #line 25 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                                                                                                                                                                   Write(p.AuthenticationType);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 26 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                </p>\r\n            </div>\r\n");

            
            #line 29 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
