#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Specter.Web;
    using Specter.Web.Core.Events;
    using Specter.Web.Core.Infrastructure;
    using Specter.Web.Framework;
    using Specter.Web.Framework.Events;
    using Specter.Web.Framework.Mvc;
    using Specter.Web.Framework.UI;
    using Specter.Web.Framework.UI.Captcha;
    using Specter.Web.Models;
    using Specter.Web.Models.Common;
    using Specter.Web.Models.Device;
    using Specter.Web.Models.Dialogs;
    using Specter.Web.Models.GeoZones;
    using Specter.Web.Models.GPS;
    using Specter.Web.Models.Map;
    using Specter.Web.Models.Notify;
    using Specter.Web.Models.User;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ConfirmEmail.cshtml")]
    public partial class _Views_Account_ConfirmEmail_cshtml : Specter.Web.Framework.ViewEngines.Razor.WebViewPage<dynamic>
    {
        public _Views_Account_ConfirmEmail_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Account\ConfirmEmail.cshtml"
  
    ViewBag.Title = "ConfirmAccount";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 5 "..\..\Views\Account\ConfirmEmail.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h2>\r\n<div>\r\n    <p>\r\n        Thank you for confirming your account. Please ");

            
            #line 8 "..\..\Views\Account\ConfirmEmail.cshtml"
                                                 Write(Html.ActionLink("click here to log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
